title = "StaticDraft.xyz"
baseURL = "https://staticdraft.xyz"
languageCode = "en-us"
theme = "ananke"
#themesDir = "../.."

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 9 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
[permalinks]
  mix = "/:year/:month/:day/:slug/"
  
[params]
  mainSections = ["blog", "log", "archive"]
  favicon = ""
  description = "running, °o°, tech, life"
  facebook = ""
  twitter = "https://twitter.com/mitchejj"
  instagram = ""
  youtube = ""
  github = "http://github.com/mitchejj"
  gitlab = ""
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-gray"
  cover_dimming_class = "bg-black-70"
#  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
#  featured_image = "http://farm4.static.flickr.com/3815/11576686014_90c73d2886_b.jpg" 
  #""http://farm6.static.flickr.com/5476/11930984426_1ce49e30b7_b.jpg"
  recent_posts_number = 3
